spring.application.name=vetpulse-backend

server.port=8081

# BD
spring.datasource.url=jdbc:postgresql://localhost:5432/vetpulse
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Fuso
app.timezone=America/Sao_Paulo
